### ISSUE TITLE
Issue - A3

### ISSUE THREAD

**Issue by Miguel-MCM** [GustavoVieiraDeAraujo/Projeto-Final-Struct-Back-End#6]
### Tasks

- Serializar as controllers;
- Fazer o RSPEC das models e controllers;
- Aumentar o povoamento do banco de dados;
- Habilitar a gem rack-cors para integração ao front;
- Implementar o sistema de autenticação (login e logout);
- Implementar o active_storage nas models dos membros, serviços e parcerias;

**Comment by GustavoVieiraDeAraujo** [comment]
### Completed
- RSPEC criado;
- Rack-cors habilitado;
- Serialização concluida;
- Povoamento realizado;
- Active-storage implementado;
- Sistema de autenticação implementado;
